# This is a basic workflow to help deploy an armory project on Itch.io

name: Itch.io Deploy Workflow

# Controls when the workflow will run
on:
  workflow_run:
    workflows: [github-deploy]
    types: [completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  itchio-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - uses: yeslayla/butler-publish-itchio-action@master
      with:
         BUTLER_CREDENTIALS: ${{ secrets.ITCH_IO_API_KEY }}
         CHANNEL: HTML
         ITCH_GAME: armory-build-test
         ITCH_USER: quantumcoderqc
         PACKAGE: html5
      
      
    
